# Generated by Django 2.2.6 on 2019-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20191016_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('On Time', 'on_time'), ('Complete', 'complete'), ('Expected Late', 'expected_late'), ('Overdue', 'overdue')], max_length=20),
        ),
    ]
