# Generated by Django 2.2.6 on 2019-10-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todoitem_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='upload',
        ),
    ]
